project_name: secrethub-cli

builds:
  - &default
    id: default
    binary: "bin/secrethub"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: ./cmd/secrethub/main.go
    ldflags:
      - -s -w -X "github.com/secrethub/secrethub-cli/internals/secrethub.Commit={{ .ShortCommit }}" -X "github.com/secrethub/secrethub-cli/internals/secrethub.Version={{ .Version }}"
    flags:
      - -tags=production
  - <<: *default
    id: "without-bin-dir"
    binary: "secrethub"

archives:
  - name_template: "secrethub-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
    files:
    - LICENSE
    - CREDITS.md

checksum:
  name_template: "secrethub-{{ .Tag }}-checksums.txt"

release:
  prerelease: true

brews:
  - name: secrethub-cli
    ids:
      - default
    tap:
      owner: secrethub
      name: homebrew-tools
    folder: Formula
    install: |
      bin.install "bin/secrethub"
    homepage: https://secrethub.io
    description: Command-line interface for SecretHub
    skip_upload: false

scoop:
  name: secrethub-cli
  bucket:
    owner: secrethub
    name: scoop-secrethub

  homepage: https://secrethub.io
  description: Command-line interface for SecretHub

  license: Apache-2.0

  skip_upload: false

nfpms:
  - file_name_template: "secrethub-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - without-bin-dir
    vendor: SecretHub
    homepage: https://secrethub.io
    description: CLI for using the SecretHub Secret Management Service
    maintainer: SecretHub Support <support@secrethub.io>
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - rpm
      - deb
    dependencies:
      - ca-certificates
    recommends:
      - xclip
    scripts:
      postinstall: "scripts/post-install.sh"
      postremove: "scripts/post-remove.sh"
