project_name: secrethub

builds:
  - binary: "secrethub"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/secrethub/main.go
    ldflags:
      - -s -w -X main.commit={{ .ShortCommit }} -X main.version={{ .Version }}
    flags:
      - -tags=production

archive:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
  bin_directory: true
  files:
  - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

brew:
  name: secrethub-cli
  github:
    owner: secrethub
    name: homebrew-tools
  folder: Formula

  homepage: https://secrethub.io
  description: Command-line interface for SecretHub

snapcraft:
  name: secrethub
  publish: true
  summary: Command-line interface for SecretHub
  description: SecretHub is a developer tool to help you keep database passwords, API tokens, and other secrets out of IT automation scripts.
  apps:
    secrethub:
      plugs:
        - network
        - personal-files
  plugs:
    personal-files:
      read:
        - $HOME/.secrethub
      write:
        - $HOME/.secrethub

scoop:
  bucket:
    owner: secrethub
    name: scoop-secrethub

  homepage: https://secrethub.io
  description: Command-line interface for SecretHub

  license: Apache-2.0
