version: 2.1
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.50.1-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - restore_cache:
          keys:
            - golangci-lint-{{ .Branch }}
            - golangci-lint-develop
      - run: golangci-lint run
      - save_cache:
          key: golangci-lint-{{ .Branch }}
          paths:
            - ~/.cache/golangci-lint
            - ~/.cache/go-build
  verify-build:
    parameters:
      os:
        type: string
      arch:
        type: string
    docker:
      - image: circleci/golang:1.18
    steps:
      - checkout
      - run: GOOS=<< parameters.os >> GOARCH=<< parameters.arch >> go build ./cmd/secrethub
  test:
    docker:
      - image: circleci/golang:1.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make test
  verify-goreleaser:
    docker:
      - image: goreleaser/goreleaser:v1.12.3
    steps:
      - checkout
      - run: goreleaser check
workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - verify-build:
          name: verify-build-<< matrix.os >>-<< matrix.arch >>
          matrix:
            parameters:
              os: ["darwin", "linux", "windows"]
              arch: ["amd64", "386"]
            exclude:
              - os: darwin
                arch: "386"
      - test
      - verify-goreleaser
